import csv

csv.Dictwriter()

# open Players.csv file with csv.DictReader and read its content into a list of dictionary, players_data
players_data = []
with open('Players.csv', 'r') as f:
    rows = csv.DictReader(f)
    for r in rows:
        players_data.append(r)

# open Teams.csv file with csv.DictReader and read its content into a list of dictionary, teams_data
teams_data = []
with open('Teams.csv', 'r') as f:
    rows = csv.DictReader(f)
    for r in rows:
        teams_data.append(r)


def average_shots(players_data: list) -> tuple:
    """Returns a tuple with four elements; the first, second, third, and
    fourth elements show the average number of shots made by defenders,
    midfielders, forwards, and goalkeepers, respectively

    Notes: the test results below are printed out with two decimal places to
    get around floating-point errors.

    >>> averages = average_shots(players_data)
    >>> type(averages)
    <class 'tuple'>
    >>> [f'{a:.2f}' for a in averages]
    ['1.16', '2.39', '4.23', '0.03']
    """
    # create a dict with key is each role and value is list of score
    score = {'defender': [], 'midfielder': [], 'forward': [], 'goalkeeper': []}
    for player in players_data:
        score[player['position']] += [int(player['shots'])]

    return tuple(sum(score[role]) / len(score[role]) for role in score)


def max_GF_GA_ratio(teams_data: list) -> str:
    """Returns the string name of a team with highest ratio of goalsFor to
    goalsAgainst

    >>> max_GF_GA_ratio(teams_data)
    'Portugal'
    """

    return max(teams_data,
               key=lambda x: int(x['goalsFor']) / int(x['goalsAgainst']))['team']


def whose_player_list(players_data: list, teams_data: list) -> list:
    """Returns a list of tuples; each tuple has information about a player who
    is on a team ranked in the top 10, plays less than 250 minutes and makes
    more than 150 passes; the format for each tuple is (player's surname, team
    played for, team ranking, minutes played, number of passes)

    >>> whose_player_list(players_data, teams_data)
    [('Veron', 'Argentina', 7, 185, 235), ('Montolivo', 'Italy', 5, 236, 163)]
    """
    # Reminder: Convert minutes and passes to integers before comparing to values

    # create a dict which key is team name and value is team ranking of top10 team
    valid_team = {team['team']: team['ranking']
                  for team in teams_data
                  if int(team['ranking']) <= 10}

    def valid(player: dict) -> bool:
        """
        check whatever
        - minute of play less than 250
        - more than 150 passes to each player
        - team in top 10 team
        """
        return int(player['minutes']) < 250 \
            and int(player['passes']) > 150 \
            and player['team'] in valid_team

    def exact_player(player: dict) -> tuple:
        """Exact a player in to tuple format"""

        return (player['surname'],
                player['team'],
                int(valid_team[player['team']]),
                int(player['minutes']),
                int(player['passes']))

        # return a nested list of tuple if valid condition of player

    return [exact_player(player) for player in players_data if valid(player)]


def team_list_shots_per_minute(players_data: list, teams_data: list):
    """Returns a list of tuples; each tuple has information about a team and
    its shots per minute value generated by its players

    Notes: the test results below are printed out with five decimal places to
    get around floating-point errors.

    >>> list_of_tuples = team_list_shots_per_minute(players_data, teams_data)
    >>> list_of_tuples.sort()
    >>> for team,shots in list_of_tuples:
    ...     print(f'{team} {shots:.5f}')
    ...
    Algeria 0.01050
    Argentina 0.01394
    Australia 0.01010
    Brazil 0.01440
    Cameroon 0.01178
    Chile 0.01152
    Denmark 0.01077
    England 0.01237
    France 0.00998
    Germany 0.01121
    Ghana 0.01337
    Greece 0.01077
    Honduras 0.00438
    Italy 0.01212
    Ivory Coast 0.01313
    Japan 0.00886
    Mexico 0.01086
    Netherlands 0.01128
    New Zealand 0.00505
    Nigeria 0.00996
    North Korea 0.01077
    Paraguay 0.00928
    Portugal 0.01263
    Serbia 0.01286
    Slovakia 0.00884
    Slovenia 0.00572
    South Africa 0.01184
    South Korea 0.01111
    Spain 0.01380
    Switzerland 0.00721
    USA 0.01282
    Uruguay 0.01118
    """

    # create a nested dict of dict which format is
    # {team_name: {'shot':number of shot, 'minutes': number of minute }}
    team_dict = {team['team']: {'shot': 0, 'minutes': 0}
                 for team in teams_data}

    # iterate over player data to plus each team and minute
    # for calculating shit per minute
    for x in players_data:
        team_dict[x['team']]['shot'] += int(x['shots'])
        team_dict[x['team']]['minutes'] += int(x['minutes'])

    return [(name, ratio['shot'] / ratio['minutes'])
            for name, ratio in team_dict.items()]


if __name__ == '__main__':
    import doctest

    doctest.testmod()
